;; -*- lexical-binding: t; -*-

(defun mpack-encode (data)
  (cond
    ((null data) (unibyte-string #xc2))
    ((eq data t) (unibyte-string #xc3))
    ((integerp data)
     (if (natnump data)
       (cond
         ((<= data 127) (unibyte-string data))
         ((<= data 255) (unibyte-string #xcc data))
         ((<= data 65535) (unibyte-string #xcd (lsh data -8) (% data 256)))
         ((<= data 4294967295) (unibyte-string #xce
                                               (lsh data -24)
                                               (% (lsh data -16) 256)
                                               (% (lsh data -8) 256)
                                               (% data 256)))
         ((<= data 18446744073709551615) (unibyte-string #xcf
                                                         (lsh data -56)
                                                         (% (lsh data -48) 256)
                                                         (% (lsh data -40) 256)
                                                         (% (lsh data -32) 256)
                                                         (% (lsh data -24) 256)
                                                         (% (lsh data -16) 256)
                                                         (% (lsh data -8) 256)
                                                         (% data 256)))
         (t (signal 'args-out-of-range (list data 0 18446744073709551615))))
       (cond
         ((>= data -32) (unibyte-string (+ #x100 data)))
         ((>= data -128) (unibyte-string #xd0 (+ #x100 data)))
         ((>= data -32768) (unibyte-string #xd1
                                           (mod (lsh data -8) 256)
                                           (mod data 256)))
         ((>= data -2147483648) (unibyte-string #xd2
                                           (mod (lsh data -24) 256)
                                           (mod (lsh data -16) 256)
                                           (mod (lsh data -8) 256)
                                           (mod data 256)))
         ((>= data -9223372036854775808) (unibyte-string #xd3
                                           (mod (lsh data -56) 256)
                                           (mod (lsh data -48) 256)
                                           (mod (lsh data -40) 256)
                                           (mod (lsh data -32) 256)
                                           (mod (lsh data -24) 256)
                                           (mod (lsh data -16) 256)
                                           (mod (lsh data -8) 256)
                                           (mod data 256)))
         (t (signal 'args-out-of-range (list data -9223372036854775808 0))))))
    ((stringp data)
     (let* ((bytes (encode-coding-string data 'utf-8))
            (len (length bytes)))
       (cond
         ((<= len 31) (concat (unibyte-string (+ #xa0 len)) bytes))
         ((<= len 255) (concat (unibyte-string #xd9 len) bytes))
         ((<= len 65535) (concat (unibyte-string #xda (lsh len -8) (% len 256)) bytes))
         ((<= len 4294967295) (concat (unibyte-string #xdb
                                                      (lsh len -24)
                                                      (% (lsh len -16) 256)
                                                      (% (lsh len -8) 256)
                                                      (% len 256))
                                      bytes))
         (t (signal 'args-out-of-range (list len 4294967295))))))
    ((floatp data)
     (let ((sign 0)
           (expo nil)
           (mant nil))
       (when (< (copysign -1.0 data) 0)
         (setq sign 1)
         (setq data (- data)))
       (cond
         ((isnan data)
          (setq expo 2047)
          (setq mant 1))
         ((= data 0)
          (setq expo 0)
          (setq mant 0))
         ((= data 1e+INF)
          (setq expo 2047)
          (setq mant 0))
         ((<= (logb data) -1023)
          (setq mant (floor (* 4503599627370496 0.5 data (expt 2.0 1023))))
          (setq expo 0))
         (t
           (setq mant (floor (* 4503599627370496 (1- (/ data (expt 2.0 (logb data)))))))
           (setq expo (+ (logb data) 1023))))
       (unibyte-string #xcb
                       (+ (* sign 128) (lsh expo -4))
                       (+ (lsh (% expo 16) 4) (lsh mant -48))
                       (% (lsh mant -40) 256)
                       (% (lsh mant -32) 256)
                       (% (lsh mant -24) 256)
                       (% (lsh mant -16) 256)
                       (% (lsh mant -8) 256)
                       (% mant 256))))
    ((vectorp data)
     (let* ((len (length data))
            (elems (mapconcat #'mpack-encode data)))
       (cond
         ((<= len 15) (concat (unibyte-string (+ #x90 len)) elems))
         ((<= len 65535) (concat (unibyte-string #xdc (lsh len -8) (% len 256)) elems))
         ((<= len 4294967295) (concat (unibyte-string #xdd
                                                      (lsh len -24)
                                                      (% (lsh len -16) 256)
                                                      (% (lsh len -8) 256)
                                                      (% len 256))
                                      elems))
         (t (signal 'args-out-of-range (list len 4294967295))))))
    ((consp data) ;TODO: what about empty map, which is just nil...
     (let* ((len (lsh (length data) -1))
            (elems (mapconcat #'mpack-encode data)))
       (cond
         ((<= len 15) (concat (unibyte-string (+ #x80 len)) elems))
         ((<= len 65535) (concat (unibyte-string #xde (lsh len -8) (% len 256)) elems))
         ((<= len 4294967295) (concat (unibyte-string #xdf
                                                      (lsh len -24)
                                                      (% (lsh len -16) 256)
                                                      (% (lsh len -8) 256)
                                                      (% len 256))
                                      elems))
         (t (signal 'args-out-of-range (list len 4294967295))))))
    (t (signal 'wrong-type-argument (list data)))))

(defun mpack-decode (data &optional pos)
  (let*
    ((pos (or pos (list -1)))
     (dbyte (aref data (setcar pos (1+ (car pos)))))
     (dinfo
       (cond
         ((<= dbyte #x7f) (cons 'const dbyte))
         ((<= dbyte #x8f) (cons 'map (- -1 (- dbyte #x80))))
         ((<= dbyte #x9f) (cons 'vec (- -1 (- dbyte #x90))))
         ((<= dbyte #xbf) (cons 'str (- -1 (- dbyte #xa0))))
         ((= dbyte #xc0)  (cons 'const :nil))
         ((= dbyte #xc1)  (cons 'const :never))
         ((= dbyte #xc2)  (cons 'const nil))
         ((= dbyte #xc3)  (cons 'const t))
         ((= dbyte #xc4)  (cons 'bin 1))
         ((= dbyte #xc5)  (cons 'bin 2))
         ((= dbyte #xc6)  (cons 'bin 4))
         ((= dbyte #xc7)  (cons 'ext 1))
         ((= dbyte #xc8)  (cons 'ext 2))
         ((= dbyte #xc9)  (cons 'ext 4))
         ((= dbyte #xca)  (cons 'float 4))
         ((= dbyte #xcb)  (cons 'float 8))
         ((= dbyte #xcc)  (cons 'uint 1))
         ((= dbyte #xcd)  (cons 'uint 2))
         ((= dbyte #xce)  (cons 'uint 4))
         ((= dbyte #xcf)  (cons 'uint 8))
         ((= dbyte #xd0)  (cons 'int 1))
         ((= dbyte #xd1)  (cons 'int 2))
         ((= dbyte #xd2)  (cons 'int 4))
         ((= dbyte #xd3)  (cons 'int 8))
         ((= dbyte #xd4)  (cons 'ext (- -1 1)))
         ((= dbyte #xd5)  (cons 'ext (- -1 2)))
         ((= dbyte #xd6)  (cons 'ext (- -1 4)))
         ((= dbyte #xd7)  (cons 'ext (- -1 8)))
         ((= dbyte #xd8)  (cons 'ext (- -1 16)))
         ((= dbyte #xd9)  (cons 'str 1))
         ((= dbyte #xda)  (cons 'str 2))
         ((= dbyte #xdb)  (cons 'str 4))
         ((= dbyte #xdc)  (cons 'vec 2))
         ((= dbyte #xdd)  (cons 'vec 4))
         ((= dbyte #xde)  (cons 'map 2))
         ((= dbyte #xdf)  (cons 'map 4))
         ((>= dbyte #xe0) (cons 'const (- dbyte #x100)))
         (t (signal 'args-out-of-range (list dbyte 0 255)))))
     (dtype (car dinfo))
     (darg (cdr dinfo))
     (dlen (if (eq dtype 'const) nil
             (if (< darg 0) (- -1 darg)
               (let ((acc 0))
                 (dotimes (_ darg acc)
                   (setq acc (+
                               (lsh acc 8)
                               (aref data (setcar pos (1+ (car pos)))))))))))
     (dtype (cond
              ((eq dtype 'ext) (setcar pos (1+ (car pos))) 'str)
              ((eq dtype 'bin) 'str)
              (t dtype))))
    (cond
      ((eq dtype 'const) darg)
      ((eq dtype 'float)
       (let* ((expo-size (if (= darg 4) 8 11))
              (mant-size (if (= darg 4) 23 52))
              (expo-bits (expt 2 expo-size))
              (mant-bits (expt 2 mant-size))
              (total-size (* 8 darg))
              (sign (if (= (lsh dlen (- (1- total-size))) 1) -1 1))
              (expo (% (lsh dlen (- mant-size)) expo-bits))
              (mant (% dlen mant-bits)))
         (cond
           ((and (= expo 0) (= mant 0)) (* sign 0.0))
           ((and (= expo (1- expo-bits)) (= mant 0)) (* sign 1e+INF))
           ((= expo (1- expo-bits)) 1e+NaN)
           (t (*
                sign
                (+ (if (= expo 0) 0.0 mant-bits) mant)
                (expt 2.0 (- expo (- (lsh expo-bits -1) (if (= expo 0) 2 1))))
                (/ 1.0 mant-bits))))))
      ((eq dtype 'uint) dlen)
      ((eq dtype 'int)
       (if (>= dlen (lsh (expt 256 darg) -1))
         (- dlen (expt 256 darg))
         dlen))
      ((eq dtype 'str)
       (setcar pos (+ (car pos) dlen))
       (decode-coding-string
         (substring data (- (1+ (car pos)) dlen) (1+ (car pos))) 'utf-8))
      ((eq dtype 'map)
       (let* ((list (make-list (* dlen 2) nil))
              (top list))
         (dotimes (_ (* dlen 2) top)
           (setcar list (mpack-decode data pos))
           (setq list (cdr list)))))
      ((eq dtype 'vec)
       (let* ((vec (make-vector dlen nil)))
         (dotimes (idx dlen vec)
           (aset vec idx (mpack-decode data pos)))))
      (t (signal 'error (list dtype dinfo dlen pos))))))

(defun mpack-decode-multi (data)
  (let ((pos (list -1)) (top '()) (bot '()))
    (while (< (1+ (car pos)) (length data))
           (if top
             (setcdr bot (list (mpack-decode data pos)))
             (setq bot (list (mpack-decode data pos)))
             (setq top bot)))
    top))

(provide 'mpack)
