;; -*- lexical-binding: t; -*-

(require 'seq)

(setq nvim-key-conv-map
      '((backspace . "BS")
        (?\t . "Tab")
        (tab . "Tab")
        (linefeed . "NL")
        (?\r . "CR")
        (return . "CR")
        (escape . "Esc")
        (?\e . "Esc")
        (space . "Space")
        (32 . "Space")
        (?< . "lt")
        (delete . "Del")
        (127 . "Del")
        (up . "Up")
        (down . "Down")
        (left . "Left")
        (right . "Right")
        (f1 .  "f1")
        (f2 .  "f2")
        (f3 .  "f3")
        (f4 .  "f4")
        (f5 .  "f5")
        (f6 .  "f6")
        (f7 .  "f7")
        (f8 .  "f8")
        (f9 .  "f9")
        (f10 . "f10")
        (f11 . "f11")
        (f12 . "f12")
        (f13 . "f13")
        (f14 . "f14")
        (f15 . "f15")
        (f16 . "f16")
        (f17 . "f17")
        (f18 . "f18")
        (f19 . "f19")
        (f20 . "f20")
        (f21 . "f21")
        (f22 . "f22")
        (f23 . "f23")
        (f24 . "f24")
        (help . "Help")
        (undo . "Undo")
        (find . "Find")
        (select . "Select")
        (insert . "Insert")
        (home . "Home")
        (end . "End")
        (prior . "PageUp")
        (next . "PageDown")
        (kp-up . "kUp")
        (kp-down . "kDown")
        (kp-left . "kLeft")
        (kp-right . "kRight")
        (kp-home . "kHome")
        (kp-end . "kEnd")
        (kp-begin . "kOrigin")
        (kp-prior . "kPageUp")
        (kp-next . "kPageDown")
        (kp-delete . "kDel")
        (kp-add . "kPlus")
        (kp-subtract . "kMinus")
        (kp-multiply . "kMultiply")
        (kp-divide . "kDivide")
        (kp-decimal . "kPoint")
        (kp-separator . "kComma")
        (kp-equal . "kEqual")
        (kp-enter . "kEnter")
        (kp-0 . "k0")
        (kp-1 . "k1")
        (kp-2 . "k2")
        (kp-3 . "k3")
        (kp-4 . "k4")
        (kp-5 . "k5")
        (kp-6 . "k6")
        (kp-7 . "k7")
        (kp-8 . "k8")
        (kp-9 . "k9")))

(setq nvim-key-conv-mod-map
      '((shift . ?S)
        (control . ?C)
        (meta . ?M)
        (alt . ?A)
        ; (meta . ?T)
        ; (hyper . ?)
        (super . ?D)))

(defun nvim-key-conv (keys)
  (mapconcat
    (lambda (key)
      (catch
        'nvim-key-conv
        (cond
          ((or (event-modifiers key) (assq (event-basic-type key) nvim-key-conv-map))
           (concat "<"
                   (mapconcat (lambda (mod)
                                (string (or
                                          (alist-get mod nvim-key-conv-mod-map)
                                          (throw 'nvim-key-conv "")
                                          ) ?-))
                              (event-modifiers key))
                   (or
                     (alist-get (event-basic-type key) nvim-key-conv-map)
                     (string (event-basic-type key)))
                   ">")
           )
          ((eq (type-of key) 'integer) (string key))
          (t (throw 'nvim-key-conv "")))))
    keys))

(provide 'nvim-key-conv)
